### ISSUE TITLE
스크롤에 따르는 액션으로 수정

### ISSUE THREAD

**Issue by ChooHongWook** [ChooHongWook/Muscle-Formula_04#6]
### ISSUE
- Group:  `client`
- Type: `refactor`
- Detail: refactor landing page

### TODO
1. [ ] 랜딩페이지 UI 수정
2. [ ] 필요한 기술 확인
3. [ ] 스크롤에 맞춰서 움직이게 수정

### Estimated time
> Pick one
`2022-09-04`

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Urgency:`Middle`
